---

#TODO: Maybe some checks here for disk size, open ports etc.
- name: Download Plesk installer
  ansible.builtin.get_url:
    url: http://autoinstall.plesk.com/plesk-installer
    dest: /root/plesk-installer
    mode: 0700

- name: Run Plesk installer
  ansible.builtin.command: /root/plesk-installer install
  args:
    creates: /usr/sbin/plesk

- name: Check whether Plesk has been configured
  ansible.builtin.command: plesk bin init_conf --check-configured
  register: result
  ignore_errors: True

- name: Run Plesk initial configuration
  ansible.builtin.command: plesk bin init_conf \
              --init \
              -passwd "{{ plesk.admin_password }}" \
              -email "{{ plesk.email }}" \
              -license_agreed true \
              -default-ip "{{ ansible_default_ipv4.address }}" \
              -ip-type shared \
              -hostname "{{ plesk.hostname }}" \
              -send_announce false \
              -company "{{ plesk.company }}" \
              -name "{{ plesk.name }}" \
              -phone "{{ plesk.phone }}" \
              -address "{{ plesk.address }}" \
              -city "{{ plesk.city }}" \
              -state "{{ plesk.state }}" \
              -zip "{{ plesk.zip }} " \
              -country "{{ plesk.country }}"
  when: result.rc == 1

- name: Disable poweruser mode
  ansible.builtin.command: plesk bin poweruser --off

- name: Install Plesk license (if specified)
  ansible.builtin.command: plesk bin license --install "{{ plesk.license }}"
  when: plesk.license != ""
