- name: Create /var/mastodon
  ansible.builtin.file:
    path: /var/mastodon
    state: directory

- name: Copy docker-compose.yml and other files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /var/mastodon/{{ item }}
    mode: 0644
  loop:
  - docker-compose.yml
  - .env.production
  - nginx.conf

- name: Copy scripts
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /var/mastodon/{{ item }}
    mode: 0755
  loop:
  - nginx.sh
  - setup.sh

- name: Deploy mastodon
  community.docker.docker_compose:
    project_src: /var/mastodon/
    files:
    - docker-compose.yml

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /var/www/vhosts/system/dedonnie.social/conf/nginx.conf

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Allow incrontab for root
  ansible.builtin.lineinfile:
    create: true
    path: /etc/incron.allow
    line: root

- name: Install incrontab for root
  ansible.builtin.lineinfile:
    create: true
    path: /var/spool/incron/root
    line: "/var/www/vhosts/system/dedonnie.social/conf/nginx.conf\tIN_CLOSE_WRITE,IN_DELETE,IN_MODIFY\t/var/mastodon/nginx.sh"
    owner: root
    group: root
    mode: '0600'

- name: Backup db
  ansible.builtin.cron:
    name: DB Backup
    hour: "*/6"
    minute: 7
    state: present
    job: /usr/bin/docker exec mastodon_db_1 su postgres bash -c "pg_dump postgres -f /backups/$(date -uIminutes).sql"

- name: Set file and dir permissions and owner for mastodon dir
  ansible.builtin.file:
    path: /var/mastodon/redis
    owner: 999
    mode: 0755

- name: Set file and dir permissions and owner for db backup dir
  ansible.builtin.file:
    path: /var/mastodon/postgres14
    owner: 70
    mode: 0700

- name: Set file and dir permissions and owner for mastodon cache dir
  ansible.builtin.file:
    path: /var/cache/mastodon/
    owner: 991
    mode: 0755

- name: Set file and dir permissions and owner for plesk mastodon dir
  ansible.builtin.file:
    path: /var/www/vhosts/dedonnie.social/mastodon
    owner: 991
    group: 1002
    mode: 02775

- name: Set file and dir permissions and owner for db backup dir
  ansible.builtin.file:
    path: /var/www/vhosts/dedonnie.social/mastodon/db_backups
    owner: 70
    group: 1002
    mode: 02775
