- name: Create /var/mastodon
  ansible.builtin.file:
    path: /var/mastodon
    state: directory

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /var/mastodon/{{ item }}
  loop:
  - docker-compose.yml
  - .env.production
  - nginx.sh
  - nginx.conf
  - setup.sh

- name: Deploy mastodon
  community.docker.docker_compose:
    project_src: /var/mastodon/
    files:
    - docker-compose.yml

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /var/www/vhosts/system/dedonnie.social/conf/nginx.conf

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Backup db
  ansible.builtin.cron:
    name: DB Backup
    hour: 5
    minute: 22
    state: present
    job: docker exec -it mastodon_db_1 su - postgres bash -c "pg_dump postgres > /backups/$(date --iso-8601).sql"

- name: Set file and dir permissions and owner for mastodon dir
  ansible.builtin.file:
    path: /var/mastodon/redis
    owner: 999
    mode: 0755

- name: Set file and dir permissions and owner for db backup dir
  ansible.builtin.file:
    path: /var/mastodon/postgres14
    owner: 70
    mode: 0700

- name: Set file and dir permissions and owner for mastodon cache dir
  ansible.builtin.file:
    path: /var/cache/mastodon/
    owner: 991
    mode: 0755

- name: Set file and dir permissions and owner for plesk mastodon dir
  ansible.builtin.file:
    path: /var/www/vhosts/dedonnie.social/mastodon
    owner: 991
    group: 1002
    mode: 02775

- name: Set file and dir permissions and owner for db backup dir
  ansible.builtin.file:
    path: /var/www/vhosts/dedonnie.social/mastodon/db_backups
    owner: 70
    group: 1002
    mode: 02775
