# code: language=ansible

- name: Packages that should always be there
  ansible.builtin.apt:
    state: present
    pkg: mosh, rsync, wget, jq, zsh, locales, python-is-python3, python3-boto3, s3cmd, git, incron
